apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gagefx-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: gagefx.com
      http:
        paths:
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: api-gateway-service
                port:
                  number: 80

          - path: /api/gages
            pathType: Prefix
            backend:
              service:
                name: api-gateway-service
                port:
                  number: 80

          - path: /api/products
            pathType: Prefix
            backend:
              service:
                name: api-gateway-service
                port:
                  number: 80

          - path: /api/calendar
            pathType: Prefix
            backend:
              service:
                name: api-gateway-service
                port:
                  number: 80
